version: '3.8'

services:
  # Service principal de l'API
  service-ia:
    build: .
    container_name: service-ia-yasserseryas
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
      - PORT=5003
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service Nginx pour le reverse proxy (optionnel)
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - service-ia
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app_data:
    driver: local
